version: '3.8'

services:
  api:
    image: jabenjam/chatgpt-api
    restart: always
    depends_on:
      - database
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/employee_management_system?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
      OPENAI_API_KEY: "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"
    ports:
      - "8080:8080"

  database:
    image: mysql:latest
    restart: always
    volumes:
      - ~/Documents/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: chatgpt
      MYSQL_USER: chatgpt
      MYSQL_PASSWORD: chatgpt
      MYSQL_DATABASE: chatgpt
    ports:
      - "3306:3306"